export const Navlist = [
  "Fresh",
  "Amazon miniTV",
  "Sell",
  "Best Seller",
  "Today's Deals",
  "Mobiles",
  "Prime",
  "Customer Serivice",
  "Electronics",
  "Fashion",
  "New Releases",
  "Home & Kitchen",
  "Amazon Pay",
  "Computers",
  "Books",
];
