export const Navlist = [
  "Fresh",
  "Amazon miniTV",
  "Sell",
  "Best Seller",
  "Today's Deals",
  "Mobiles",
  "Prime",
  "Customer Serivice",
  "Electronics",
  "Fashion",
  "New Releases",
  "Home & Kitchen",
  "Amazon Pay",
  "Computers",
  "Books",
];

export const categories = [
  "Electronics",
  "Mobile Phone",
  "Laptops",
  "Accessories",
  "Headphones",
  "Food",
  "Books",
  "Clothes/Shoes",
  "Beauty/Health",
  "Sports",
  "Outdoor",
  "Home",
];
