import banner1 from "/assets/banner2.jpg";
import banner2 from "/assets/banner2.jpg";
import banner3 from "/assets/banner3.jpg";
import banner4 from "/assets/banner4.jpg";
import banner5 from "/assets/banner5.jpg";
import banner6 from "/assets/banner6.jpg";
import emptycart from "/assets/amazon_empty_cart.png";
import cart from "/assets/amazon_cart.png";
import location from "/assets/amazon_location.png";
import search from "/assets/amazon_search.png";
import logo from "/assets/amazon_logo.png";
import ph1 from "/assets/ph1.jpg";
import ph2 from "/assets/ph2.jpg";
import ph3 from "/assets/ph3.jpg";
import ph4 from "/assets/ph4.jpg";
import tv1 from "/assets/tv1.jpg";
import tv2 from "/assets/tv2.jpg";
import tv3 from "/assets/tv3.jpg";
import tv4 from "/assets/tv4.jpg";
import im1 from "/assets/im1.jpg";
import profileimg from "/assets/unknownprofile.png";

export const ban1 = banner1;
export const ban2 = banner2;
export const ban3 = banner3;
export const ban4 = banner4;
export const ban5 = banner5;
export const ban6 = banner6;
export const empty_cart = emptycart;
export const amazon_cart = cart;
export const amazon_location = location;
export const amazon_search = search;
export const amazon_logo = logo;
export const phone1 = ph1;
export const phone2 = ph2;
export const phone3 = ph3;
export const phone4 = ph4;
export const smarttv1 = tv1;
export const smarttv2 = tv2;
export const smarttv3 = tv3;
export const smarttv4 = tv4;
export const Gff = im1;
export const unknownprofile = profileimg