name: Deploy MERN App to Azure VM

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker buildx build --push --tag ${{ secrets.DOCKER_HUB_USERNAME }}/amazon-clone-frontend:latest --file frontend/Dockerfile frontend
          docker buildx build --push --tag ${{ secrets.DOCKER_HUB_USERNAME }}/amazon-clone-backend:latest --file backend/Dockerfile backend

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub and pull images
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Pull and deploy Docker containers on self-hosted VM
        run: |

          cd /home/azureuser/application/
          export MONGO_URL=${{ secrets.MONGO_URL }}
          export SMTP_USER=${{SMTP_USER}}
          export SMTP_PASSWORD=${SMTP_PASSWORD}
          docker-compose down
          docker-compose up -d
