name: Deploy MERN App to Azure VM

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_PASSWORD}}

      - name: Build and push Docker images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/amazon-clone-frontend:latest --file frontend/Dockerfile frontend
          docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/amazon-clone-backend:latest --file backend/Dockerfile backend

      - name: Deploy to Azure VM
        env:
          AZURE_SSH_KEY: ${{ secrets.VM_SSH_KEY }}
          AZURE_SSH_USER: ${{ secrets.VM_SSH_USER }}
          AZURE_SSH_HOST: ${{ secrets.VM_SSH_HOST }}
        run: |
          echo "${AZURE_SSH_KEY}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no $AZURE_SSH_USER@$AZURE_SSH_HOST << EOF
            echo "Pulling latest Docker images and restarting containers..."
            cd /path/to/your/app
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker image prune -f
          EOF
